✨ add decrypt functionality and fzf file select

diff --git a/scripts/cry b/scripts/cry
--- a/scripts/cry
+++ b/scripts/cry
@@ -1,30 +1,39 @@
 #!/bin/bash
+#declare file="${!#}"
 declare subcommand="$1"; shift
+#declare subCmd=false
+git status &>/dev/null || { echo "Warning: This script only works within a git repo"; exit 1; }
+
+## FIXME find a way to only use this git cmd that i need anf if it fails
+#exit program instead of using git status
+#if git rev-parse --show-toplevel
+
 
 declare projectPath="$(git rev-parse --show-toplevel)"
 declare projectName="${projectPath##*/}"
 ## create a key for every project you wanna use and name it `age-keygen -o "key-nameOfGitRepo"`
 export SOPS_AGE_KEY_FILE="$PRIVATE/bin/age/key-$projectName"
-## FIXME If no subcommand given just edit the encrypted file directly
-## I need to be able to get this to work editing encrypted files is the
-#best
-[[ -z "$2" ]] && sops "$1"
-## create a command with autocompletion
-echo $1
-echo $2
-echo $0
-echo $subcommand
+#[[ -z "$2" ]] && sops "$file"
+## FIXME currently the `fzf` file select works only if files from PWD are
+#selected make all cmds work even for files that are not just in PWD but
+#from root git dir throughout whole repo.
 decrypt() {
-  # TODO: decrypt the file and create a new decrypted file
-  echo hello world
+  ##FIXME only add an extension if the filename has a dot
+  local file="$(fzf)"
+  local extension="${file##*.}"
+  local filename="${file%%.*}"
+  local dot="."
+  sops --decrypt "$file" > "${filename}${dot}$extension"
+  #sops --decrypt "$file" > "fasdi"
 }
 
 cat() {
-  ## TODO: make it so it accepts all file types
-  sops --decrypt --input-type yaml --output-type yaml "$1" 
+  local file="$(fzf)"
+  sops --decrypt "$file"
 }
 
 partial-encrypt() {
+  local file="$(fzf)"
   echo no
   ##TODO: create command for partial encryption of file, (just password) with regex
   echo "key1: value1" >  test_regex.yaml
@@ -35,37 +44,39 @@ partial-encrypt() {
 }
 
 encrypt() {
-  keyPath="$PRIVATE/bin/age/key-$projectName"
-  publicKey="$(\grep -oP "public key: \K(.*)" $keyPath)"
-  filename=$(basename -- "$1")
-  extension="${filename##*.}"
-  filename="${filename%.*}"
-  sops --encrypt --age "$publicKey" "$1" > "$filename.enc.$extension"
-
-  #sops --encrypt --age $(cat "$keyPath" |grep -oP "public key: \K(.*)") --input-type "$extension" --output-type "$extension" "$1" > "$filename.enc.$extension"
-  #sops --encrypt --age $(cat "$keyPath" | \grep -oP "public key: \K(.*)") $2 $3 $1 > "$filename.enc.$extension"
-  #sops --encrypt --age age1a2cmrn2f8jfcfx7mwgycnxcsgtwvu73sck2ak03h3na0r753e5dshvknrf secret.yaml
-  ## rm regular file after encrypting it
-  #rm "$1"
+  local file="$(fzf)"
+  local keyPath="$PRIVATE/bin/age/key-$projectName"
+  local publicKey="$(\grep -oP "public key: \K(.*)" $keyPath)"
+  ##FIXME only add an extension if the filename has a dot
+  local extension="${file##*.}"
+  local filename="${file%.*}"
+  ## FIXME current does not show up in tab complete, I would need a multi
+  #layer tab completion. Works for now
+  echo $1
+  if [[ "$1" == "current" ]]; then
+    ## If you want to encrypted the given file without creating a new
+    #file
+    sops --encrypt --in-place --age "$publicKey" "$file"
+  else
+    sops --encrypt --age "$publicKey" "$file" > "$filename.enc.$extension"
+  fi
+}
+edit() {
+  ## directly edit encrypted file, my fav. sops feature!
+  local file="$(fzf)"
+  sops "$file"
 }
 
-encrypt-itself() {
-  keyPath="$PRIVATE/bin/age/key-$projectName"
-  publicKey="$(\grep -oP "public key: \K(.*)" $keyPath)"
-  filename=$(basename -- "$1")
-  extension="${filename##*.}"
-  filename="${filename%.*}"
-  sops --encrypt --in-place --age "$publicKey" "$1"
-}
 
 ## function call from $1 argument
-declare -a commands=(decrypt cat partial-encrypt encrypt encrypt-itself)
+declare -a commands=(decrypt cat partial-encrypt encrypt edit )
 for i in ${commands[@]}; do
-  if [[ $i == "$subcommand" ]]; then
+  if [[ "$i" == "$subcommand" ]]; then
+    #subCmd=true
     "$subcommand" $*
-    exit 0
   fi
 done
+#[[ "$subCmd" = false ]] && __edit
 
 # Tab completion - add to bashrc: complete -C sopsi sopsi
 if [ -n "$COMP_LINE" ]; then
